---
title: "Pilot Study"
author: "Benny"
date: "October 28, 2017"
output: html_document
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)

#install.packages("httr")  # once per machine
library("httr")

<<<<<<< HEAD
query.params <- list(query = "restaurant", location = "47.6610, -122.3134",
 key="AIzaSyA0OM7dRXjjaEaf__06DaRZbfkza9jW1vw")
response <- GET("https://maps.googleapis.com/maps/api/place/textsearch/json?query=", query = query.params)
response
=======
query.params <- list(query="restuarants", location="-33.8670522,151.1957362", key="AIzaSyA0OM7dRXjjaEaf__06DaRZbfkza9jW1vw")

response <- GET("https://maps.googleapis.com/maps/api/place/textsearch/json?query=", query = query.params)
>>>>>>> a6066daec56ee146cda2bc88f99dc517160519c6

```

```{r}
# Flattern data in order to be read by R
#install.packages("jsonlite")  # once per machine
library("jsonlite")

test <- fromJSON("https://maps.googleapis.com/maps/api/place/textsearch/json?query=restaurant&location=47.6610%2C%20-122.3134&price_level=3&rating=4.3&key=AIzaSyA0OM7dRXjjaEaf__06DaRZbfkza9jW1vw")

View(test[3])
```


